# Generated by Django 3.0.6 on 2020-05-20 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about_us', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Тип эл. адреса')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия')),
            ],
            options={
                'verbose_name': 'Тип е-мейла',
                'verbose_name_plural': 'Типы е-мейлов',
            },
        ),
        migrations.CreateModel(
            name='EmailSendingFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата завяления')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='about_us.Customer', verbose_name='Клиент')),
                ('type', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.EmailType', verbose_name='Тип эл. адреса')),
            ],
            options={
                'verbose_name': 'Отправленный е-мейл',
                'verbose_name_plural': 'Отправленные е-мейлы',
            },
        ),
    ]
