# Generated by Django 3.0.6 on 2020-05-20 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок новости')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Фото')),
                ('tittle', models.TextField(max_length=512, verbose_name='Краткое описание к новости')),
                ('description', models.TextField(blank=True, max_length=2056, verbose_name='Текст новости')),
                ('available', models.BooleanField(default=False, verbose_name='Актуальность')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
