# Generated by Django 3.0.6 on 2020-05-20 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=True, max_length=32, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Фамилия')),
                ('message', models.TextField(blank=True, default=None, max_length=2056, null=True, verbose_name='Отзыв')),
                ('image', models.ImageField(blank=True, upload_to='reviews/%Y/%m/%d', verbose_name='Фото')),
                ('available', models.BooleanField(default=True, verbose_name='Актуальность отзыва')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания отзыва')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created'],
            },
        ),
    ]
