# Generated by Django 3.0.6 on 2020-05-20 13:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Фамилия')),
                ('office', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Должность')),
                ('position', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Позиция')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Номер тел.')),
                ('dob', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рожд-я')),
                ('country', models.CharField(blank=True, default='Россия', max_length=64, null=True, verbose_name='Страна')),
                ('town', models.CharField(blank=True, default='Курск', max_length=64, verbose_name='Город')),
                ('image', models.ImageField(blank=True, upload_to='experts/%Y/%m/%d', verbose_name='Фото')),
                ('description', models.TextField(blank=True, default=None, max_length=512, null=True, verbose_name='Описание деятельности')),
                ('available', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('vk', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка VK')),
                ('instagram', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка instagram')),
                ('twitter', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка twitter')),
                ('facebook', models.URLField(blank=True, default=None, max_length=1024, null=None, verbose_name='Ссылка facebook')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования записи')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
