# Generated by Django 3.0.6 on 2020-05-20 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название выполненного объекта')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, upload_to='portfolio_avatar/%Y/%m/%d', verbose_name='Аватар объекта')),
                ('description', models.TextField(blank=True, max_length=2056, verbose_name='Описание работ')),
                ('available', models.BooleanField(default=False, verbose_name='Актуальность')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('created', 'name'),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='portfolios/%Y/%m/%d', verbose_name='Доп. фото')),
                ('available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активный?')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('portfolio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Подробная информация к объекту',
                'verbose_name_plural': 'Подробная информация к объекту',
            },
        ),
    ]
